config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :admins, controllers: {sessions: 'admin/sessions', passwords: 'admin/passwords', :registrations => "admin/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :home do
    post 'inquiry' => 'home#inquiry', on: :collection
  end
  get 'about', to: "home#about", as: 'about'
  get 'contact', to: "home#contact", as: 'contact'
  get 'privacy', to: "home#privacy", as: 'privacy'

  resources :constructions, only: [:index, :show]

  namespace :admin do
    root to: 'home#index'
    resources :constructions, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/construction.rb
class Construction < ApplicationRecord
  mount_uploader :image, ConstructionImageUploader
  mount_uploader :image_2, ConstructionImageUploader
  mount_uploader :image_3, ConstructionImageUploader
  mount_uploader :image_4, ConstructionImageUploader
  mount_uploader :image_5, ConstructionImageUploader
  mount_uploader :image_6, ConstructionImageUploader
  mount_uploader :image_7, ConstructionImageUploader
  mount_uploader :image_8, ConstructionImageUploader
  mount_uploader :image_9, ConstructionImageUploader
  mount_uploader :image_10, ConstructionImageUploader
  # mount_uploaders :picture, PictureUploader


  validates :name, :design, :area, :type, :built_year, :filter, :type, :image, :image_2, :image_3, presence: true
  # has_many :pictures, dependent: :destroy
  # accepts_nested_attributes_for :pictures
  belongs_to :type
  belongs_to :filter

end

app/controllers/admin/constructions_controller.rb
class Admin::ConstructionsController < Admin::ApplicationController
  before_action :set_construction, only: [:show, :edit, :update, :destroy]

  def new
    @construction = Construction.new
    # @construction.pictures.build
  end

  def create
    @construction = Construction.new(construction_params)
    if @construction.save
      redirect_to constructions_path
    else
      render 'new'
    end
  end

  def edit
    # @construction.pictures.build if @construction.pictures.blank?
  end

  def update
    if @construction.update(construction_params)
      redirect_to construction_path(@construction)
    else
      render "edit"
    end
  end

  def destroy
    @construction.destroy
    redirect_to constructions_path
  end


  private

  def set_construction
    @construction = Construction.find(params[:id])
  end

  def construction_params
    params[:construction].permit(
      :name,
      :design,
      :area,
      :type_id,
      :built_year,
      :introduction,
      :filter_id,
      :image,
      :image_2,
      :image_3,
      :image_4,
      :image_5,
      :image_6,
      :image_7,
      :image_8,
      :image_9,
      :image_10,
      # :remove_image,
      # :remove_image_2,
      # :remove_image_3,
      :remove_image_4,
      :remove_image_5,
      :remove_image_6,
      :remove_image_7,
      :remove_image_8,
      :remove_image_9,
      :remove_image_10
      # pictures_attributes: [
      #   :id,
      #   :pictures
      # ]
    )
  end

end

app/controllers/constructions_controller.rb
class ConstructionsController < ApplicationController

  def index
    @constructions = Construction.all
    # @constructions = Construction.all.page(params[:page]).per(9)
  end

  def show
    @construction = Construction.find(params[:id])
  end

end

app/controllers/login/construction_controller.rb
class Login::ConstructionsController < Login::ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  def index
    @constructions = Construction.all
  end

  def show
  end

  def new
    @construction = Construction.new
    @construction.pictures.build
  end

  def create
    @construction = Construction.new(construction_params)
    if @construction.save
      redirect_to constructions_path
    else
      render 'new'
    end
  end

  def edit
    @construction.pictures.build if @construction.pictures.blank?
  end

  def update
    if @construction.update(construction_params)
      redirect_to construction_path(@construction)
    else
      render "edit"
    end
  end

  def destroy
  end


  private

  def set_construction
    @construction = Construction.find(params[:id])
  end

  def construction_params
    params[:construction].permit(
      :name,
      :design,
      :area,
      :built_year,
      :introduction,
      :image,
      pictures_attributes: [
        :id,
        :picture
      ]
    )
  end

end

app/controllers/login/constructions_controller.rb
class Login::ConstructionsController < Login::ApplicationController
  before_action :set_construction, only: [:show, :edit, :update, :destroy]

  def new
    @construction = Construction.new
    # @construction.pictures.build
  end

  def create
    @construction = Construction.new(construction_params)
    if @construction.save
      redirect_to constructions_path
    else
      render 'new'
    end
  end

  def edit
    # @construction.pictures.build if @construction.pictures.blank?
  end

  def update
    if @construction.update(construction_params)
      redirect_to construction_path(@construction)
    else
      render "edit"
    end
  end

  def destroy
  end


  private

  def set_construction
    @construction = Construction.find(params[:id])
  end

  def construction_params
    params[:construction].permit(
      :name,
      :design,
      :area,
      :type_id,
      :built_year,
      :introduction,
      :filter_id,
      :image,
      :image_2,
      :image_3,
      :image_4,
      :image_5,
      :image_6,
      :image_7,
      :image_8
      # pictures_attributes: [
      #   :id,
      #   :pictures
      # ]
    )
  end

end

app/helpers/constructions_helper.rb
module ConstructionsHelper
end

app/views/constructions/index.html.haml
%main#main
  / ======= Breadcrumbs =======
  %section#breadcrumbs.breadcrumbs
    .container
      .d-flex.justify-content-between.align-items-center
        %h2 Construction
        %ol
          %li
            = link_to 'Home', root_path
          %li
            = link_to 'Projects', constructions_path
  / End Breadcrumbs
  / ======= Portfolio Section =======
  %section#portfolio.portfolio
    .container
      .section-title
        %h2 施工事例
        %p Recent Projects
      .row
        .col-lg-12.d-flex.justify-content-center
          %ul#portfolio-flters
            %li.filter-active{"data-filter" => "*"} All
            %li{"data-filter" => ".filter-home"} 住宅
            %li{"data-filter" => ".filter-shop"} 店舗
            %li{"data-filter" => ".filter-other"} OTHER
      .row.portfolio-container
        -@constructions.each do |construction|
          -# .col-lg-4.col-md-6.portfolio-item.filter-card
          .col-lg-4.col-md-6.portfolio-item{class: "filter-#{construction.filter.name}"}
            .portfolio-wrap
              = image_tag construction.image_url, class: 'img-fluid'
              .portfolio-info
                %p #{construction.name}
                .portfolio-links
                  = link_to construction_path(construction) do
                    %i.bx.bx-link
      -# =paginate @constructions
      -# .blog
      -#   .blog-pagination{"data-aos" => "fade-up"}
      -#     %ul.justify-content-center
      -#       %li.disabled
      -#         %i.bx.bxs-chevron-left
      -#       %li
      -#         %a{:href => "#"} 1
      -#       %li.active
      -#         %a{:href => "#"} 2
      -#       %li
      -#         %a{:href => "#"} 3
      -#       %li
      -#         %a{:href => "#"}
      -#           %i.bx.bxs-chevron-right
    / End Portfolio Section
/ End #main
-if admin_signed_in?
  %section
    .container
      .row
        .col-lg-12.construction.mb-5
          = link_to 'ADD NEW PROJECT', new_admin_construction_path, class: 'btn-box btn-new'

app/views/constructions/show.html.haml
%main#main
  / ======= Breadcrumbs =======
  %section#breadcrumbs.breadcrumbs
    .container
      .d-flex.justify-content-between.align-items-center
        %h2 Construction
        %ol
          %li
            = link_to 'Home', root_path
          %li 施工事例
  / ======= Portfolio Details Section =======
  %section#portfolio-details.portfolio-details
    .container
      .row
        .col-lg-8
          %h2.portfolio-title #{@construction.name}
          .owl-carousel.portfolio-details-carousel
            = image_tag @construction.image_url
            = image_tag @construction.image_2_url
            = image_tag @construction.image_3_url
        .col-lg-4.portfolio-info
          %h3 #{@construction.name}
          %ul
            %li
              %strong> 地域
              \　: #{@construction.area}
            %li
              %strong> 設計
              \　: #{@construction.design}
            %li
              %strong> タイプ
              \　: #{@construction.type.name}
            %li
              %strong> 竣工
              \　: #{@construction.built_year}
          %p
            #{@construction.introduction}
    .portfolio
      .container
        .row.portfolio-container
          .col-lg-4.col-md-6.portfolio-item.filter-card
            .portfolio-wrap
              =image_tag @construction.image_url, class: 'img-fluid'
              .portfolio-info
                .portfolio-links
                  %a.venobox{"data-gall" => "portfolioGallery", :href => @construction.image_url}
                    %i.bx.bx-plus
          -(2..10).each do |i|
            .col-lg-4.col-md-6.portfolio-item.filter-card
              .portfolio-wrap
                -if @construction.try("image_#{i}_url").present?
                  =image_tag @construction.try("image_#{i}_url"), class: 'img-fluid'
                  .portfolio-info
                    .portfolio-links
                      %a.venobox{"data-gall" => "portfolioGallery", :href => @construction.try("image_#{i}_url")}
                        %i.bx.bx-plus
    .container.mt-5
      -if admin_signed_in?
        .row
          .col-6.construction
            = link_to 'EDIT THIS PROJECT', edit_admin_construction_path(@construction), class: 'btn-box btn-edit'
          .col-6.construction.text-right
            = link_to 'DELETE', admin_construction_path(@construction), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn-box btn-delete'
      .row
        .col-lg-12.construction
          %p.mt-5.ml-2
            =link_to 'BACK TO THE LIST', constructions_path