config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  devise_for :admins, controllers: {sessions: 'admin/sessions', passwords: 'admin/passwords', :registrations => "admin/registrations"}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :home do
    post 'inquiry' => 'home#inquiry', on: :collection
  end
  get 'about', to: "home#about", as: 'about'
  get 'contact', to: "home#contact", as: 'contact'
  get 'privacy', to: "home#privacy", as: 'privacy'

  resources :constructions, only: [:index, :show]

  namespace :admin do
    root to: 'home#index'
    resources :constructions, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception
  # #herokuapp.comから独自ドメインへリダイレクト
  # before_filter :ensure_domain
  # FQDN = 'www.aiojapanoo.com'
  # #redirect correct server from herokuapp domain for SEO
  # def ensure_domain
  #   return unless /\.herokuapp.com/ =~ request.host
  #   #主にlocalテスト用の対策80と443以外でアクセスされた場合ポート番号をURLに含める
  #   port = ":#{request.port}" unless [80, 443].include?(request.port)
  #   redirect_to "#{request.protocol}#{FQDN}#{port}#{request.path}", status: :moved_permanently
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.haml
/ ======= Footer =======
%footer#footer
  .footer-top
    .container
      .row
        .col-lg-4.col-md-6
          .footer-info
            %h3 AIO. JAPAN Co., LTd
            %p
              兵庫県 姫路市
              %br/
              上手野 338-2
              %br/
              %br/
              %strong Phone:
              = link_to "090-1440-6947", "tel:09014406947"
              %br/
              %strong Email:
              = link_to "info@f-copo.com", "mailto:info@f-copo.com"
              %br/
            .social-links.mt-3
              %a.facebook{:href => "#"}
                %i.bx.bxl-facebook
              %a.instagram{:href => "#"}
                %i.bx.bxl-instagram
        .col-lg-2.col-md-6.footer-links
          %h4 Useful Links
          %ul
            %li
              %i.bx.bx-chevron-right
              = link_to 'ホーム', root_path
            %li
              %i.bx.bx-chevron-right
              = link_to '会社案内', about_path
            %li
              %i.bx.bx-chevron-right
              = link_to '施工事例', constructions_path
            %li
              %i.bx.bx-chevron-right
              = link_to '個人情報保護方針', privacy_path
            %li
              %i.bx.bx-chevron-right
              = link_to 'お問い合わせ', contact_path
        .col-lg-3.col-md-6.footer-links
          %h4 Links
          %ul
            %li
              %i.bx.bx-chevron-right
              = link_to 'フジモトコーポレーション', 'https://f-copo.com/'
            %li
              %i.bx.bx-chevron-right
              = link_to '中村建築研究室 エヌラボ(n-lab)', 'https://n-lab.name/'
            %li
              %i.bx.bx-chevron-right
              = link_to '永森建築事務所', 'https://ynagamo.com/'
            %li
              %i.bx.bx-chevron-right
              = link_to '（有）エステートホームズ', 'http://www.estate-h.com/'

        .col-lg-3.col-md-6.footer-links.footer-newsletter
          %h4 To Worker
          %ul
            -if admin_signed_in?
              %li
                = link_to 'Add New Project',new_admin_construction_path
              %li
                = link_to 'Logout', destroy_admin_session_path
            -else
              %li
                %i.bx.bx-walk
                = link_to 'AIO. JAPANs', new_admin_session_path
              -# %li
              -#   = link_to 'Sign Up', new_admin_registration_path

  .container
    .copyright
      \© Copyright
      = succeed "." do
        %strong
          %span Sailor
    .credits
      / All the links in the footer should remain intact.
      / You can delete the links only if you purchased the pro version.
      / Licensing information: https://bootstrapmade.com/license/
      / Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/sailor-free-bootstrap-theme/
      Designed by
      %a{:href => "https://bootstrapmade.com/"} BootstrapMade
/ End Footer
%a.back-to-top{:href => "#"}
  %i.bx.bxs-chevron-up

app/views/application/_header.html.haml
/ ======= Header =======
%header#header.fixed-top
  .container.d-flex.align-items-center
    %a.logo{:href => root_path }
      %img.img-fluid{:alt => "", :src => "/img/aio_logo_s.png"}
    %h1.logo-h1
      = link_to 'AIO. JAPAN', root_path
    / Uncomment below if you prefer to use an image logo
    %nav.nav-menu.d-none.d-lg-block
      %ul
        %li.active
          = link_to 'HOME', root_path
        %li
          = link_to 'PROJECTS', constructions_path
        %li
          = link_to 'ABOUT', about_path
        %li
          = link_to 'CONTACT', contact_path
    / .nav-menu
    -# %a.get-started-btn.ml-auto{:href => "index.html"} Get Started
    .contact-info.ml-auto.d-none.d-lg-block
      %i.bx.bxs-envelope.margin-10px-right
        = link_to "info@f-copo.com", "mailto:info@f-copo.com"
      %i.bx.bxs-phone
        = link_to "09014406947", "tel:09014406947"